version: '3.8'

services:
  backend:
    build:
      context: .
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_URL: "jdbc:postgresql://db:5432/gestao_projetos"
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      db:
        condition: service_healthy
    
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gestao_projetos
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: 
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    